spring:
  threads.virtual.enabled: true

server:
  address: localhost
  port: 8080
  ssl:
    enabled: false

logging:
  level:
    de.phlup.circuitchaos: info

circuit-chaos:
  game:
    options:
      max-number-of-computer-players: 1
    waiting-times-in-milliseconds:
      time-between-steps: 1_000
      time-to-show-explosions: 500
      question-timeout: 3600_000
      sleep-time-between-answer-polling: 100
      animation-steps: 20
  server:
    clean-game-list-scheduler:
      start-delay-seconds: 1800
      fixed-rate-seconds: 300
      evict-time-preparing-minutes: 30
      evict-time-running-minutes: 60
  client:
    own-url: http://localhost:8080
    server-url: http://localhost:8080
    allow-others-to-start-a-game: false
    sound: true
    ssl-bundle: ""
    default-board-size-x: 900
    default-board-size-y: 880
    default-theme: "default"
    default-zoom: 1
    default-modules:
      - "MAIN_LASER"
      - "HOVERCRAFT"
    board-directories:
      - "classpath:boards"
      - "file:boards"
      - "file:temp"
    themes:
      ki-lowres:
        name: "ki-lowres"
        path: "classpath:themes/ki-lowres"
        open-floor-variants: 8
        water-variants: 8
        explosion-variants: 7
        glue-variants: 12
        oil-variants: 12
        pusher-animation-steps: 10
        repulsor-animation-steps: 9
        zoom-factor: 1
        image-size: 40
      ki-hires:
        name: "ki-hires"
        path: "classpath:themes/ki-hires"
        open-floor-variants: 8
        water-variants: 8
        explosion-variants: 7
        glue-variants: 12
        oil-variants: 12
        pusher-animation-steps: 10
        repulsor-animation-steps: 9
        zoom-factor: 0.15
        image-size: 400
    poll-scheduler:
      start-delay-milliseconds: 1000
      fixed-rate-milliseconds: 100
